
FROM public.ecr.aws/docker/library/amazonlinux:latest

EXPOSE 162
EXPOSE 80

RUN yum -y install net-snmp-utils

RUN mkdir -p /opt/trapmux/bin /opt/trapmux/etc /opt/trapmux/log
COPY trapmux /opt/trapmux/bin
COPY tools/process_csv_data.sh /opt/trapmux/bin
COPY tools/trapmux.conf /opt/trapmux/etc

# Install root bash history
COPY tools/docker/root_bash_history /root/.bash_history
COPY tools/docker/root_vimrc /root/.vimrc

CMD ["/opt/trapmux/bin/trapmux", "-c", "/opt/trapmux/etc/trapmux.yml"]
